lc_basic_packages:
  - apt-transport-https
  - htop
  - iotop
  - iftop
  - ncdu
  - curl
  - wget
  - bash-completion
  - vim
  - mtr-tiny
  - git
  - unzip
lc_exim_packages:
  - exim4
  - exim4-base
  - exim4-config
  - exim4-daemon-light
