---
namespace: "nixknight"
name: "opentofu"
version: "0.1.2"
readme: "README.md"
authors:
    - "Saad Ali <engr.saadali786@gmail.com>"
description: "Ansible collection for OpenTofu"
license:
  - "MIT"
tags:
    - opentofu
    - terraform
