---
namespace: "nixknight"
name: "general"
version: "0.1.0"
readme: "README.md"
authors:
    - "Saad Ali <engr.saadali786@gmail.com>"
description: "Ansible collection for general plugins and roles"
license:
  - "MIT"
tags:
    - general
    - linux
