---
dependencies: []
galaxy_info:
  author: Saad Ali
  description: Setup a service with Docker Compose.
  license: MIT
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - docker
    - compose
