---
- name: Stop and Disable Service
  ansible.builtin.systemd:
    name: "{{ DOCKER_COMPOSE_SERVICE_NAME }}"
    state: stopped
    enabled: false

- name: Remove Systemd Service File
  ansible.builtin.file:
    path: "{{ DOCKER_COMPOSE_SERVICE_SYSTEMD_FILE }}"
    state: absent

- name: Remove Service Docker Compose File
  ansible.builtin.file:
    path: "{{ DOCKER_COMPOSE_SERVICE_COMPOSE_PATH }}"
    state: absent
    recurse: true

- name: Remove service configuration directory
  ansible.builtin.file:
    path: "{{ DOCKER_COMPOSE_SERVICE_CONFIG_PATH }}"
    state: absent
    recurse: true
  when: DOCKER_COMPOSE_SERVICE_CONFIG_PATH is defined and DOCKER_COMPOSE_SERVICE_CONFIG_PATH | length > 0

- name: Remove additional directories for the service
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
    recurse: true
  with_items: "{{ DOCKER_COMPOSE_SERVICE_ADDITIONAL_PATHS }}"
  when: DOCKER_COMPOSE_SERVICE_ADDITIONAL_PATHS is defined and DOCKER_COMPOSE_SERVICE_ADDITIONAL_PATHS | length > 0
