---
# tasks file for Ansible-Docker-Compose-Service
# Uses nixknight.docker.docker_image_mgmt_plan from this collection.
- name: Create a Docker Container Image Management Plan
  nixknight.docker.docker_image_mgmt_plan:
    images: "{{ DOCKER_COMPOSE_SERVICE_IMAGES }}"
    purge: "{{ DOCKER_COMPOSE_SERVICE_REMOVE }}"
    force_refresh: "{{ DOCKER_COMPOSE_SERVICE_FORCE_IMAGE_REFRESH }}"
  register: container_image_mgmt_plan

- name: Set Vars according to the Image Management Plan
  ansible.builtin.set_fact:
    container_images_to_pull: "{{ container_image_mgmt_plan.docker_images_to_pull }}"
    container_images_to_remove: "{{ container_image_mgmt_plan.docker_images_to_remove }}"
    service_needs_to_stop: "{{ container_image_mgmt_plan.docker_images_to_remove | length > 0 }}"
