---
# tasks file for Ansible-Docker-Compose-Service
- name: Create/Update Service
  ansible.builtin.include_tasks:
    file: create_update_service.yml
  when: not DOCKER_COMPOSE_SERVICE_REMOVE

- name: Delete/Remove Service
  ansible.builtin.include_tasks:
    file: delete_service.yml
  when: DOCKER_COMPOSE_SERVICE_REMOVE
