---
- name: Pull New Container Images
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull
    state: present
  with_items: "{{ container_images_to_pull }}"
  when: container_images_to_pull | length > 0

- name: Remove Old Container Images
  community.docker.docker_image:
    name: "{{ item }}"
    state: absent
  with_items: "{{ container_images_to_remove }}"
  when: service_needs_to_stop
